import { createSlice } from '@reduxjs/toolkit'

const initialState: StoryInterface = {
  '1': {
    'title': 'Sự ra đời của sao Bóng',
    'content': `
      <p>Con người cố gắng đi thật xa để tìm kiếm sự sống ngoài trái đất nhưng không biết rằng có một ngôi sao đã từng tồn tại ở ngay chính ngân hà này. Sau khi vật chất được hình thành năm tỷ năm, ở trung tâm dải ngân hà Milky Way, các thiên thạch, bụi và băng đã hình thành một ngôi sao khổng lồ có lực hút gấp ba trăm lần mặt trời của trái đất. Quả cầu này đã hút bốn vệ tinh xung quanh chính là bốn mặt trời bao gồm: Hỏa Nhật, Phong Nhật, Băng Nhật, Lôi Nhật đại diện cho bốn nguyên tố Lửa - Gió - Sét - Băng. Bốn mặt trời xoay quanh và khiến ngôi sao này không bao giờ có ban đêm.</p>
      <p>Một tỷ năm sau, vi khuẩn đã tiến hóa thành những quả bóng có tư duy và suy nghĩ như con người, họ đã đặt cho ngôi sao này là ngôi sao Bóng. Trên sao Bóng xuất hiện hai chủng tộc là chủng tộc Nghệ và chủng tộc Ngải. Chủng tộc Nghệ rất thông minh, họ phát triển khoa học kỹ thuật và rất giỏi về chế tạo vũ khí, tên lửa. Trong khi chủng tộc Ngải được hình thành sau và lạc hậu hơn. Ban đầu các chủng tộc này sống rất hòa thuận. Nhưng càng ngày sự phát triển của tộc Nghệ càng bỏ xa tộc Ngải.</p>
      <p>Vì thế thủ lĩnh của tộc Ngải là Tăn Voàn đã lên đường sang tộc Nghệ để học hỏi. Một ngày nọ, bóng ta vào một cửa hàng sách và thấy cuốn sách "1001 cách làm giàu". Khi mở trang đầu tiên, cuốn sách ấy nói rằng: "Nếu bạn muốn trở nên giàu có thì hãy đầu tư vào trí tuệ, hãy phát triển khoa học". Trong đầu bóng ta nảy lên một suy nghĩ rằng tộc Nghệ rất thông minh, công nghệ của họ cũng hiện đại. Thay vì đầu tư trí tuệ cả trăm năm thì chiếm luôn tộc Nghệ chẳng phải nhanh hơn hay sao?</p> 
      <p>Bóng ta trở về và họp bàn bới các bô bô lão. Các bô bô lão nói rằng tộc Nghệ quá mạnh, nếu đấu trực tiếp chắc chắn sẽ không có ưu thế. Nhận thấy tộc mình có khả năng về chơi ngải và làm phép nên cần phải khuếch đại sức mạnh này. Để khuếch đại cần phải tìm về nguồn gốc của sức mạnh. Đó chính là bốn mặt trời. Có một điều cấm kỵ mà tổ tiên để lại rằng: "Sự sống của sao Bóng dựa vào sự cân bằng của bốn mặt trời, nếu lấy đi sức mạnh của những mặt trời này thì năng lượng sẽ bị hỗn loạn, dẫn đến sự diệt vong của ngôi sao". Phớt lờ điều đó, họ đã triệu tập năm trăm nghìn quả bóng tộc Ngải tạo ra quả Bóng lớn. Quả bóng đó hút năng lượng của các mặt trời và các Ngải sư có thể sử dụng trong chiến tranh. Việc khuếch đại đã hoàn tất, tuy nhiên nếu gây chiến thì con cháu ngàn đời sau không phục các cụ. Chính vì thế họ đã tạo ra một cái cớ để gây chiến mà bóng bị đem ra làm con mồi chính là tộc trưởng Tăn Voàn. Vì sự phát triển của tộc, sự hy sinh của Tăn Voàn là cần thiết. Một buổi sáng, Tăn Voàn lại lên đường sang tộc Nghệ để tiếp tục tìm hiểu văn hóa - đời sống dân chúng bên đó. Chuyến đi lần này không yên bình như lần trước. Vong Lăn - một bô bô lão đã cử thuộc hạ bám sát Tăn Voàn để tìm cách ám sát. Kế hoạch là sẽ cho Tăn Voàn ăn lá ngón, sau khi ăn lá này xong thì Tăn Voàn sẽ múa quạt không ngừng nghỉ đến chết. Tên thuộc hạ đóng giả làm chủ quán ăn - nơi mà Tăn Voàn nghỉ chân. Thay vì đưa cho Tăn Voàn đĩa rau xuống xào tỏi thì hắn ta lại mang cho Tăn Voàn món lá ngón trộn ngải kim cương. Tăn Voàn ăn xong thì múa may quay cuồng, các bóng dân ở đó xúm lại xem thì không ngờ Tăn Voàn nhảy múa đẹp vô cùng. Tất cả đều tấm tắc vỗ tay. Dựa vào kỹ năng lên đồng, xuống ruộng bao năm chinh chiến của Tăn Voàn thì vài cái lá ngón có là gì. Tăn voàn đã làm phép đẩy chất độc ra khỏi cơ thể. Kế hoạch không thành công, tên thuộc hạ lủi đi mất. Tưởng những mọi việc đã yên ổn, thì đám fan hâm mộ cuồng nhiệt quá lao đến ôm Tăn Voàn và khiến bóng ta ngạt thở chết. Tên thuộc hạ biết điều đó hí hửng về nhà để viết kịch bản để báo lại cho bô bô lão lĩnh thưởng.</p>
      <p>Việc Tăn Voàn qua đời ngay trên đất tộc Nghệ đã được lan truyền đến tất cả mọi bóng. Lúc này, Vong Lăn gửi thư yêu cầu tộc vương Xa Thế của tộc Nghệ phải chịu trách nhiệm vì điều này. Họ yêu cầu bên tộc Nghệ phải bồi thường một trăm ngàn Nghệ kim. Nhưng khoản tiền đó quá lớn, tộc vương Xa Thế đã cử sứ giả sang tộc Ngải để đàm phán. Sứ giả có đi mà không có về khiến cho tộc vương Xa Thế vô cùng tức giận. Biết trước chiến sự sẽ nổ ra, tộc vương Xa Thế triệu tập 108 vị bóng tấn công biên giới phía bắc của tộc Ngải. Về phía tộc ngải, sứ giả của tộc Nghệ vẫn còn sống. Bởi vì hắn được cho chơi ngải bằng những viên ngải kim cương nên phê đến tận nóc, nửa đêm còn định mò ra chuồng thú ngủ. Bóng dân tộc Nghệ biết tin quốc tộc vương Xa Thế cho người tấn công tộc Ngải mà không có lý do chính đáng nên đã quay lưng lại với tộc vương. Vì tộc Nghệ lúc này đã bị suy yếu, không những chống trả lại sự tấn công ở bên giới, tộc Ngải đem bóng sang tấn công Tộc Nghệ. Khói lửa, đau thương và mất mát của cả hai bên kéo dài trăm ngày không đêm. Cuối cùng, để không tổn thất quá nhiều cho cả hai bên, họ đã quyết định tổ chức ra những trận đấu để phân định tộc xứng đáng tồn tại trên ngôi sao Bóng. Bóng đại diện của tộc Ngải là Cà Xân - một dân chơi hệ Ngải thực thục khi mà hắn có cả bốn nguyên tốc sức mạnh trong cơ thể. Hơn nữa, hắn đã bú một nửa số năng lượng của mặt trời trong bóng nên sức mạnh tăng gấp một lần. Bên tộc Nghệ, con của tộc Vương là Bạn Ơi đã sẵn sàng ứng chiến. Súng tầm ngắn, xích trói, bom và Rocket đã sẵn sàng.</p>
      <p>Ngày giao chiến đã đến, họ cùng nhảy lên võ đài. Khi tiếng hô vang lên, họ lao vào đánh đấm nhau túi bụi mà không dùng đến phép hay vũ khí. Vì sức mạnh thể chất của Bạn Ơi chiếm ưu thế, Cà Xân đã bị đánh ngã xuống. Ngay lập tức Cà Xân tụ khí và bắn ra một quả cầu lửa khiến Bạn ơi bị cháy mất cái áo khoác hiệu con cá sấu. Bạn Ơi lùi lại phía sau và rút súng bắn. Cà Xân lộn vài vòng né đạn rất ngải, các quả bóng xem vỗ tay ào ào. Nhưng lộn đến lần thứ chín thì cơn đau lưng tái phát, Cà Xân bị khựng lại một nhịp khiến đạn bắn trúng vai của quả bóng đang xem phía sau, lập tức hắn bị đăng xuất khỏi trái đất. Những viên đạn tiếp theo Bạn Ơi bắn ra bị Cà Xân sử dụng nguyên tố phong để đẩy lùi. Biết đạn damage không bằng phép của Cà Xân, Bạn Ơi lôi luôn Rocket ra để kết thúc trận đấu. Rocket nhanh chóng bay đến Cà Xân, hắn bình tĩnh triệu tập sức mạnh của Băng Nhật để đóng băng quả Rocket to bằng một góc sàn đấu. Rõ ràng cả hai bên cân tài cân sức, Bạn Ơi rút sợi xích ra ném về phía Cà Xân định trói hắn. Cà Xân bắt được sợi xích và triệu tập sức mạnh của Lôi Nhật truyền sét thẳng vào sợi xích. Bạn Ơi bị giật tung bóng và ngã ra. Cà Xân lao đến một chiêu sét ngàn vôn để nướng Bạn Ơi thì bỗng từ đâu lao đến một chiếc gậy bay thẳng vào mặt của Cà Xân. Hắn bị choáng một lúc vì tuy lực của chiếc gậy. Mọi bóng quay sang nhìn thì thấy có một quả bóng trông khá bụi bậm, bên kiếm bên rìu, sau lưng đại đao to lớn. Trông hắn thật kỳ lạ, hắn không sử dụng phép thuật, cũng không sử dụng vũ khí công nghệ cao. Vậy hắn là ai? hắn từ nơi nào đến? Có phải trên sao Bóng này có một tộc khác nữa hay không? To be continued...`
  }
}
export const Story = createSlice({
  name: 'story',
  initialState,
  reducers: {
  }
});

export const { } = Story.actions;
export default Story.reducer;
